[package]
name = "browserslist-rs"
version = "0.3.0"
authors = ["Pig Fang <g-plane@hotmail.com>"]
edition = "2021"
description = "Rust-ported browserslist."
repository = "https://github.com/g-plane/browserslist-rs"
license = "MIT"
keywords = ["web", "javascript"]
categories = ["web-programming", "config"]
include = ["/data", "**/*.rs", "Cargo.toml"]

[lib]
name = "browserslist"
crate-type = ["cdylib", "rlib"]

[dependencies]
either = "1.6"
itertools = "0.10"
napi = { version = "2.0.0-alpha.3", features = ["serde-json"], optional = true }
napi-derive = { version = "2.0.0-alpha.4", optional = true }
once_cell = "1.8"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
clap = "2.33"
test-case = "1.2"

[build-dependencies]
anyhow = "1.0"
itertools = "0.10"
napi-build = { version = "1.1", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "2.3", features = ["json"] }

[features]
node = ["napi", "napi-derive", "napi-build"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
chrono = { version = "0.4", features = ["wasmbind"] }
js-sys = "0.3"
serde-wasm-bindgen = "0.3"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
chrono = "0.4"
