name: lint

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo clippy
      - run: cargo clippy --example inspect
      - run: cargo clippy --tests
